[project]
name = "mipi"
version = "0.1.0"
description = "🎵 `mipi`: A configurable command line MIDI processor 🎵"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mido>=1.3.3",
]

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "pytest>=8.4.0",
    "ruff>=0.11.13",
]
